name: Deploy Traffic VM

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-traffic-vm.yml'
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'Name for the Traffic VM'
        required: false
        default: 'traffic-vm'
      machine_type:
        description: 'Machine type for the VM'
        required: false
        default: 'e2-standard-2'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  ZONE: us-central1-a

jobs:
  deploy-traffic-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Create startup script
      run: |
        cat > startup-script.sh << 'EOF'
        #!/bin/bash
        set -e

        # Update system
        apt-get update
        apt-get install -y python3 python3-pip curl wget jq
        
        # Install Node.js 18.x (required for Claude Code CLI)
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs

        # Install mitmproxy
        pip3 install mitmproxy

        # Install Claude Code CLI
        echo "Installing Claude Code CLI..."
        npm install -g @anthropic-ai/claude-code
        
        # Add npm global bin to PATH and create symlink
        NPM_GLOBAL_BIN=$(npm config get prefix)/bin
        echo "export PATH=\$PATH:$NPM_GLOBAL_BIN" >> /etc/profile
        ln -sf $NPM_GLOBAL_BIN/claude /usr/local/bin/claude
        
        # Create traffic user
        useradd -m -s /bin/bash traffic
        
        # Create directories for logs and certificates
        mkdir -p /opt/traffic/{logs,certs}
        chown -R traffic:traffic /opt/traffic

        # Generate traffic proxy certificates
        sudo -u traffic mitmproxy --set confdir=/opt/traffic/certs &
        TRAFFIC_PID=$!
        sleep 5
        kill $TRAFFIC_PID || true

        # Install traffic CA certificate to system trust store
        cp /opt/traffic/certs/mitmproxy-ca-cert.pem /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
        update-ca-certificates

        # Create traffic proxy script
        cat > /opt/traffic/traffic_script.py << 'SCRIPT_EOF'
        import json
        import datetime
        from mitmproxy import http

        def request(flow: http.HTTPFlow) -> None:
            log_entry = {
                "timestamp": datetime.datetime.now().isoformat(),
                "type": "request",
                "method": flow.request.method,
                "url": flow.request.pretty_url,
                "headers": dict(flow.request.headers),
                "content": flow.request.content.decode('utf-8', errors='ignore') if flow.request.content else ""
            }
            
            with open("/opt/traffic/logs/traffic.jsonl", "a") as f:
                f.write(json.dumps(log_entry) + "\n")

        def response(flow: http.HTTPFlow) -> None:
            log_entry = {
                "timestamp": datetime.datetime.now().isoformat(),
                "type": "response",
                "status_code": flow.response.status_code,
                "url": flow.request.pretty_url,
                "headers": dict(flow.response.headers),
                "content": flow.response.content.decode('utf-8', errors='ignore') if flow.response.content else ""
            }
            
            with open("/opt/traffic/logs/traffic.jsonl", "a") as f:
                f.write(json.dumps(log_entry) + "\n")
        SCRIPT_EOF

        chown traffic:traffic /opt/traffic/traffic_script.py

        # Create iptables setup script
        cat > /opt/traffic/setup-iptables.sh << 'IPTABLES_EOF'
        #!/bin/bash
        echo "Setting up iptables rules for transparent interception..."
        # Exclude traffic user from redirection to prevent loops
        sudo iptables -t nat -A OUTPUT -m owner --uid-owner traffic -j RETURN
        # Redirect HTTP traffic to mitmproxy
        sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 8080
        # Redirect HTTPS traffic to mitmproxy
        sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to-port 8080
        echo "iptables rules configured for transparent mode"
        IPTABLES_EOF
        
        chmod +x /opt/traffic/setup-iptables.sh
        
        # Create cleanup script to clear iptables rules
        cat > /opt/traffic/clear-iptables.sh << 'CLEANUP_EOF'
        #!/bin/bash
        echo "Clearing iptables OUTPUT rules..."
        sudo iptables -t nat -F OUTPUT
        echo "iptables OUTPUT rules cleared - traffic interception disabled"
        CLEANUP_EOF
        
        chmod +x /opt/traffic/clear-iptables.sh
        
        # Create startup helper script for manual use
        cat > /opt/traffic/start-proxy.sh << 'SCRIPT_EOF'
        #!/bin/bash
        echo "Starting traffic proxy on port 8080..."
        echo "Log file: /opt/traffic/logs/traffic.jsonl"
        echo "To stop: Press Ctrl+C"
        echo ""
        sudo -u traffic mitmdump -s /opt/traffic/traffic_script.py --set confdir=/opt/traffic/certs --listen-port 8080 --mode transparent
        SCRIPT_EOF
        
        chmod +x /opt/traffic/start-proxy.sh

        # Create log cleanup script
        cat > /opt/traffic/cleanup-logs.sh << 'CLEANUP_LOGS_EOF'
        #!/bin/bash
        echo "Clearing traffic logs..."
        sudo -u traffic rm -f /opt/traffic/logs/traffic.jsonl
        sudo -u traffic touch /opt/traffic/logs/traffic.jsonl
        echo "Traffic logs cleared"
        CLEANUP_LOGS_EOF
        
        chmod +x /opt/traffic/cleanup-logs.sh

        # Configure NODE_EXTRA_CA_CERTS
        echo "export NODE_EXTRA_CA_CERTS=/opt/traffic/certs/mitmproxy-ca-cert.pem" >> /etc/profile
        
        echo "Traffic VM setup completed successfully"
        
        # Auto-start traffic proxy on boot
        echo "Setting up iptables and starting traffic proxy..."
        /opt/traffic/setup-iptables.sh
        nohup /opt/traffic/start-proxy.sh > /opt/traffic/logs/startup.log 2>&1 &
        echo "Traffic proxy started automatically"
        
        EOF

        chmod +x startup-script.sh

    - name: Create or Update Traffic VM
      run: |
        VM_NAME="${{ github.event.inputs.vm_name || 'traffic-vm' }}"
        MACHINE_TYPE="${{ github.event.inputs.machine_type || 'e2-standard-2' }}"
        
        # Always delete existing instance if it exists
        if gcloud compute instances describe $VM_NAME --zone=${{ env.ZONE }} >/dev/null 2>&1; then
          echo "Deleting existing instance"
          gcloud compute instances delete $VM_NAME --zone=${{ env.ZONE }} --quiet
          
          # Wait for deletion to complete
          echo "Waiting for deletion to complete..."
          while gcloud compute instances describe $VM_NAME --zone=${{ env.ZONE }} >/dev/null 2>&1; do
            echo "Still deleting..."
            sleep 5
          done
          echo "Instance deleted successfully"
        fi
        
        # Create new instance
        echo "Creating new Traffic VM: $VM_NAME"
        gcloud compute instances create $VM_NAME \
          --zone=${{ env.ZONE }} \
          --machine-type=$MACHINE_TYPE \
          --image-family=ubuntu-2204-lts \
          --image-project=ubuntu-os-cloud \
          --boot-disk-size=50GB \
          --boot-disk-type=pd-standard \
          --tags=traffic-vm,http-server,https-server \
          --metadata-from-file startup-script=startup-script.sh \
          --scopes=https://www.googleapis.com/auth/cloud-platform

    - name: Create firewall rules
      run: |
        # Allow SSH access
        gcloud compute firewall-rules create allow-ssh-traffic \
          --allow tcp:22 \
          --source-ranges 0.0.0.0/0 \
          --target-tags traffic-vm \
          --description "Allow SSH to Traffic VM" || echo "Firewall rule already exists"
        
        # Allow HTTP/HTTPS for testing
        gcloud compute firewall-rules create allow-http-https-traffic \
          --allow tcp:80,tcp:443,tcp:8080 \
          --source-ranges 0.0.0.0/0 \
          --target-tags traffic-vm \
          --description "Allow HTTP/HTTPS to Traffic VM" || echo "Firewall rule already exists"

    - name: Get VM Information
      run: |
        VM_NAME="${{ github.event.inputs.vm_name || 'traffic-vm' }}"
        echo "VM Details:"
        gcloud compute instances describe $VM_NAME --zone=${{ env.ZONE }} --format="table(name,status,machineType.basename(),networkInterfaces[0].accessConfigs[0].natIP:label=EXTERNAL_IP)"

    - name: Cleanup
      run: rm -f startup-script.sh